### ISSUE TITLE
Unable to erase flash Elio Iot (ESPTOOL-922)

### ISSUE THREAD

**Issue by Brombos** [espressif/esptool#1009]
### Operating System

Ubuntu 24.04.1 LTS

### Esptool Version

esptool.py v4.7.0

### Python Version

Python 3.12.3

### Chip Description

ESP 32 S3

### Device Description

An [Elio Iot Demo](https://elioiot.com/demo/) kit

### How is Esptool Run

Ubuntu Linux Terminal

### Full Esptool Command Line that Was Run

esptool --chip esp32s3 --port /dev/ttyACM0 erase_flash

### Esptool Output

```shell
Serial port /dev/ttyACM0
Connecting...TRACE +0.000 command op=0x08 data len=36 wait_response=1 timeout=0.100 data=
    0707122055555555 5555555555555555 | ... UUUUUUUUUUUU
    5555555555555555 5555555555555555 | UUUUUUUUUUUUUUUU
    55555555                          | UUUU
TRACE +0.015 Write 46 bytes: 
    c000082400000000 0007071220555555 | ...$........ UUU
    5555555555555555 5555555555555555 | UUUUUUUUUUUUUUUU
    5555555555555555 5555555555c0     | UUUUUUUUUUUUU.
TRACE +0.001 Read 1 bytes: c0
TRACE +0.000 Read 27 bytes: 
    0108040007071220 00000000c0c00108 | ....... ........
    0400070712200000 0000c0           | ..... .....
TRACE +0.000 Received full packet: 010804000707122000000000
TRACE +0.000 Received full packet: 010804000707122000000000
TRACE +0.000 Read 14 bytes: c0010804000707122000000000c0
TRACE +0.000 Received full packet: 010804000707122000000000
TRACE +0.000 Read 28 bytes: 
    c001080400070712 2000000000c0c001 | ........ .......
    0804000707122000 000000c0         | ...... .....
TRACE +0.000 Received full packet: 010804000707122000000000
TRACE +0.000 Received full packet: 010804000707122000000000
TRACE +0.000 Read 28 bytes: 
    c001080400070712 2000000000c0c001 | ........ .......
    0804000707122000 000000c0         | ...... .....
TRACE +0.000 Received full packet: 010804000707122000000000
TRACE +0.000 Received full packet: 010804000707122000000000
TRACE +0.000 Read 14 bytes: c0010804000707122000000000c0
TRACE +0.000 Received full packet: 010804000707122000000000

TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=00100040
TRACE +0.000 Write 14 bytes: c0000a04000000000000100040c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a04000900000000000000c0
TRACE +0.000 Received full packet: 010a04000900000000000000
TRACE +0.000 command op=0x14 data len=0 wait_response=1 timeout=3.000 data=
TRACE +0.000 Write 10 bytes: c00014000000000000c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 33 bytes: 
    0114180009000000 0000000000000000 | ................
    0000000c09000000 0000000000000000 | ................
    c0                                | .
TRACE +0.000 Received full packet: 
    0114180009000000 0000000000000000 | ................
    0000000c09000000 0000000000000000 | ................
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=4cf1ce3f
TRACE +0.000 Write 14 bytes: c0000a0400000000004cf1ce3fc0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a04000400000000000000c0
TRACE +0.000 Received full packet: 010a04000400000000000000
TRACE +0.000 command op=0x09 data len=16 wait_response=1 timeout=3.000 data=b0800060a13ad850ffffffff00000000
TRACE +0.000 Write 26 bytes: 
    c000091000000000 00b0800060a13ad8 | ............`.:.
    50ffffffff000000 00c0             | P.........
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010904000400000000000000c0
TRACE +0.000 Received full packet: 010904000400000000000000
TRACE +0.000 command op=0x09 data len=16 wait_response=1 timeout=3.000 data=9880006000000000ffffffff00000000
TRACE +0.000 Write 26 bytes: 
    c000091000000000 0098800060000000 | ............`...
    00ffffffff000000 00c0             | ..........
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010904000400000000000000c0
TRACE +0.000 Received full packet: 010904000400000000000000
TRACE +0.000 command op=0x09 data len=16 wait_response=1 timeout=3.000 data=b080006000000000ffffffff00000000
TRACE +0.000 Write 26 bytes: 
    c000091000000000 00b0800060000000 | ............`...
    00ffffffff000000 00c0             | ..........
TRACE +0.000 Read 14 bytes: c0010904000400000000000000c0
TRACE +0.000 Received full packet: 010904000400000000000000
TRACE +0.000 command op=0x09 data len=16 wait_response=1 timeout=3.000 data=b88000602a311d8fffffffff00000000
TRACE +0.000 Write 26 bytes: 
    c000091000000000 00b88000602a311d | ............`*1.
    8fffffffff000000 00c0             | ..........
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010904000400000000000000c0
TRACE +0.000 Received full packet: 010904000400000000000000
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=b4800060
TRACE +0.000 Write 14 bytes: c0000a040000000000b4800060c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a04000000b08400000000c0
TRACE +0.000 Received full packet: 010a04000000b08400000000
TRACE +0.000 command op=0x09 data len=16 wait_response=1 timeout=3.000 data=b48000600000b084ffffffff00000000
TRACE +0.000 Write 26 bytes: 
    c000091000000000 00b48000600000b0 | ............`...
    84ffffffff000000 00c0             | ..........
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010904000000b08400000000c0
TRACE +0.000 Received full packet: 010904000000b08400000000
TRACE +0.000 command op=0x09 data len=16 wait_response=1 timeout=3.000 data=b880006000000000ffffffff00000000
TRACE +0.000 Write 26 bytes: 
    c000091000000000 00b8800060000000 | ............`...
    00ffffffff000000 00c0             | ..........
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010904000000b08400000000c0
TRACE +0.000 Received full packet: 010904000000b08400000000
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=58700060
TRACE +0.000 Write 14 bytes: c0000a04000000000058700060c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a040090cc047800000000c0
TRACE +0.000 Received full packet: 010a040090cc047800000000
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=50700060
TRACE +0.000 Write 14 bytes: c0000a04000000000050700060c0
TRACE +0.000 Read 14 bytes: c0010a04000000040200000000c0
TRACE +0.000 Received full packet: 010a04000000040200000000
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=58700060
TRACE +0.000 Write 14 bytes: c0000a04000000000058700060c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a040090cc047800000000c0
TRACE +0.000 Received full packet: 010a040090cc047800000000
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=58700060
TRACE +0.000 Write 14 bytes: c0000a04000000000058700060c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a040090cc047800000000c0
TRACE +0.000 Received full packet: 010a040090cc047800000000
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=50700060
TRACE +0.000 Write 14 bytes: c0000a04000000000050700060c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a04000000040200000000c0
TRACE +0.000 Received full packet: 010a04000000040200000000
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=50700060
TRACE +0.000 Write 14 bytes: c0000a04000000000050700060c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a04000000040200000000c0
TRACE +0.000 Received full packet: 010a04000000040200000000
Chip is ESP32-S3 (QFN56) (revision v0.1)
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=50700060
TRACE +0.000 Write 14 bytes: c0000a04000000000050700060c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a04000000040200000000c0
TRACE +0.000 Received full packet: 010a04000000040200000000
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=54700060
TRACE +0.000 Write 14 bytes: c0000a04000000000054700060c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a0400c87ab1ac00000000c0
TRACE +0.000 Received full packet: 010a0400c87ab1ac00000000
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=54700060
TRACE +0.000 Write 14 bytes: c0000a04000000000054700060c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a0400c87ab1ac00000000c0
TRACE +0.000 Received full packet: 010a0400c87ab1ac00000000
Features: WiFi, BLE, Embedded PSRAM 8MB (AP_3v3)
Crystal is 40MHz
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=44700060
TRACE +0.000 Write 14 bytes: c0000a04000000000044700060c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a04008c6c951800000000c0
TRACE +0.000 Received full packet: 010a04008c6c951800000000
TRACE +0.000 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=48700060
TRACE +0.000 Write 14 bytes: c0000a04000000000048700060c0
TRACE +0.000 Read 1 bytes: c0
TRACE +0.000 Read 13 bytes: 010a04008534000000000000c0
TRACE +0.000 Received full packet: 010a04008534000000000000
MAC: 34:85:18:95:6c:8c
Traceback (most recent call last):
  File "/usr/bin/esptool", line 37, in <module>
    esptool._main()
  File "/usr/lib/python3/dist-packages/esptool/__init__.py", line 1139, in _main
    main()
  File "/usr/lib/python3/dist-packages/esptool/__init__.py", line 751, in main
    esp = esp.run_stub()
          ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/esptool/loader.py", line 996, in run_stub
    stub = StubFlasher(get_stub_json_path(self.CHIP_NAME))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/esptool/loader.py", line 159, in __init__
    with open(json_path) as json_file:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/esptool/targets/stub_flasher/stub_flasher_32s3.json'
```

### I Have Read the Troubleshooting Guide

- [x] I confirm I have read the troubleshooting guide.

**Comment by Brombos** [comment]
I tried using the source python files not the terminal command and it worked
