### ISSUE TITLE
ImportError: 'module' object has no attribute '_main'

### ISSUE THREAD

**Issue by soswow** [espressif/esptool#194]
So, I tried to install manually. both with Py2 and Py3.
I think I figured out how to workaround and what is the problem. Unfortunately I still don't know why this is happening, should it happen, and is it just my local machine setup problem or not.

After installation upon `esptool.py -h` I get this:
```
Traceback (most recent call last):
  File "/Users/sasha/anaconda/envs/py27/bin/esptool.py", line 11, in <module>
    load_entry_point('esptool==2.0b2', 'console_scripts', 'esptool.py')()
  File "/Users/sasha/anaconda/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/sasha/anaconda/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/Users/sasha/anaconda/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/Users/sasha/anaconda/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2312, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute '_main'
```

I've went into this line and found this:
```python
module = __import__(self.module_name, fromlist=['__name__'], level=0)
        try:
            return functools.reduce(getattr, self.attrs, module)
        except AttributeError as exc:
            raise ImportError(str(exc))
```
I've modified it a bit:
```python
print(self.module_name)
print(module)
print(dir(module))
```

The result is this:
```
esptool
<module 'esptool' from '/Users/sasha/anaconda/envs/py27/bin/esptool.py'>
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__requires__', 'load_entry_point', 're', 'sys']
```
or `esptool.pyc` when run second time.

Content of generated `esptool.py` is this:
```python
#!/Users/sasha/anaconda/envs/py27/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'esptool==2.0b2','console_scripts','esptool.py'
__requires__ = 'esptool==2.0b2'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('esptool==2.0b2', 'console_scripts', 'esptool.py')()
    )
```
Ans so, what I suspect is happening, for some reason instead of loading `/Users/sasha/anaconda/envs/py27/lib/python2.7/site-packages/esptool-2.0b2-py2.7.egg/esptool.pyc` it loads itself essentially.

## Temp FIX
I've modified `setup.py` a bit:
```
'console_scripts': [
            'esptool2.py=esptool:_main',
            'espsecure2.py=espsecure:_main',
            'espefuse2.py=espefuse:_main',
        ],
```

Now I need to run `esptool2.py -h` and it works.

**Comment by projectgus** [comment]
Thanks for the detailed report @soswow.

As you've found, this was a regression in #184 on POSIX platforms. Testing a fix now.
