### ISSUE TITLE
Timeout under windows

### ISSUE THREAD

**Issue by ftoyon** [espressif/esptool#261]
I want flash ESP32 without installing the esp-idf.

I try to use esptool but it's fail whit time out.
```
c:\...>esptool.py --chip esp32 --port COM7 --baud 921600 read_mac
esptool.py` v2.2
Connecting...
Traceback (most recent call last):
  File "C:\Python36\Scripts\esptool.py-script.py", line 11, in <module>
    load_entry_point('esptool==2.2', 'console_scripts', 'esptool.py')()
  File "c:\python36\lib\site-packages\esptool.py", line 2585, in _main
    main()
  File "c:\python36\lib\site-packages\esptool.py", line 2313, in main
    esp.connect(args.before)
  File "c:\python36\lib\site-packages\esptool.py", line 397, in connect
    last_error = self._connect_attempt(mode=mode, esp32r0_delay=False)
  File "c:\python36\lib\site-packages\esptool.py", line 377, in _connect_attempt
    self.sync()
  File "c:\python36\lib\site-packages\esptool.py", line 331, in sync
    timeout=SYNC_TIMEOUT)
  File "c:\python36\lib\site-packages\esptool.py", line 272, in command
    self.write(pkt)
  File "c:\python36\lib\site-packages\esptool.py", line 241, in write
    self._port.write(buf)
  File "c:\python36\lib\site-packages\serial\serialwin32.py", line 323, in write
    raise writeTimeoutError
serial.serialutil.SerialTimeoutException: Write timeout
```
the "same" command on the same computer but from esp-idf environement is working :
```
$ python ${IDF_PATH}/components/esptool_py/esptool/esptool.py --chip esp32 --port /dev/COM7 --baud 921600 read_mac
esptool.py v2.0
Connecting.....
Chip is ESP32D0WDQ6 (revision 1)
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
MAC: 24:0a:c4:09:64:84
Hard resetting...
```

**Comment by projectgus** [comment]
Hmm, that's odd! I've not seen a "write timeout" before.

* For your "not IDF" environment, can you please post the output of "python -v"?

* In the IDF environment, can you confirm you're using mingw32.exe (ie the prompt should say MINGW32 in large letters). If you specify the port as `--port COM7` inside IDF as well, does this make any difference?

**Comment by ftoyon** [comment]
For esp-idf environment I'm using the mingw32.exe and it's working fine.

The result of python -v under windows command line
```
c:\...>python -v C:\msys32\home\Frederic\esp\esp-idf-v3.0-rc1\components\esptool_py\esptool\esptool.py --chip esp32 --port COM7 --baud 921600 read_mac
import _frozen_importlib # frozen
import _imp # builtin
import sys # builtin
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
# C:\Python36\lib\encodings\__pycache__\__init__.cpython-36.pyc matches C:\Python36\lib\encodings\__init__.py
# code object from 'C:\\Python36\\lib\\encodings\\__pycache__\\__init__.cpython-36.pyc'
# C:\Python36\lib\__pycache__\codecs.cpython-36.pyc matches C:\Python36\lib\codecs.py
# code object from 'C:\\Python36\\lib\\__pycache__\\codecs.cpython-36.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A4299E8>
# C:\Python36\lib\encodings\__pycache__\aliases.cpython-36.pyc matches C:\Python36\lib\encodings\aliases.py
# code object from 'C:\\Python36\\lib\\encodings\\__pycache__\\aliases.cpython-36.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5A2630>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A41EF28>
# C:\Python36\lib\encodings\__pycache__\utf_8.cpython-36.pyc matches C:\Python36\lib\encodings\utf_8.py
# code object from 'C:\\Python36\\lib\\encodings\\__pycache__\\utf_8.cpython-36.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5B36A0>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Python36\lib\encodings\__pycache__\latin_1.cpython-36.pyc matches C:\Python36\lib\encodings\latin_1.py
# code object from 'C:\\Python36\\lib\\encodings\\__pycache__\\latin_1.cpython-36.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5B3B00>
# C:\Python36\lib\__pycache__\io.cpython-36.pyc matches C:\Python36\lib\io.py
# code object from 'C:\\Python36\\lib\\__pycache__\\io.cpython-36.pyc'
# C:\Python36\lib\__pycache__\abc.cpython-36.pyc matches C:\Python36\lib\abc.py
# code object from 'C:\\Python36\\lib\\__pycache__\\abc.cpython-36.pyc'
# C:\Python36\lib\__pycache__\_weakrefset.cpython-36.pyc matches C:\Python36\lib\_weakrefset.py
# code object from 'C:\\Python36\\lib\\__pycache__\\_weakrefset.cpython-36.pyc'
import '_weakrefset' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5BA9E8>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5BA0B8>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5B3CC0>
# C:\Python36\lib\__pycache__\site.cpython-36.pyc matches C:\Python36\lib\site.py
# code object from 'C:\\Python36\\lib\\__pycache__\\site.cpython-36.pyc'
# C:\Python36\lib\__pycache__\os.cpython-36.pyc matches C:\Python36\lib\os.py
# code object from 'C:\\Python36\\lib\\__pycache__\\os.cpython-36.pyc'
import 'errno' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Python36\lib\__pycache__\stat.cpython-36.pyc matches C:\Python36\lib\stat.py
# code object from 'C:\\Python36\\lib\\__pycache__\\stat.cpython-36.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5E1630>
# C:\Python36\lib\__pycache__\ntpath.cpython-36.pyc matches C:\Python36\lib\ntpath.py
# code object from 'C:\\Python36\\lib\\__pycache__\\ntpath.cpython-36.pyc'
# C:\Python36\lib\__pycache__\genericpath.cpython-36.pyc matches C:\Python36\lib\genericpath.py
# code object from 'C:\\Python36\\lib\\__pycache__\\genericpath.cpython-36.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5ED588>
import 'ntpath' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5E1CF8>
# C:\Python36\lib\__pycache__\_collections_abc.cpython-36.pyc matches C:\Python36\lib\_collections_abc.py
# code object from 'C:\\Python36\\lib\\__pycache__\\_collections_abc.cpython-36.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5EDB38>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5D05C0>
# C:\Python36\lib\__pycache__\_sitebuiltins.cpython-36.pyc matches C:\Python36\lib\_sitebuiltins.py
# code object from 'C:\\Python36\\lib\\__pycache__\\_sitebuiltins.cpython-36.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5D09B0>
# C:\Python36\lib\__pycache__\sysconfig.cpython-36.pyc matches C:\Python36\lib\sysconfig.py
# code object from 'C:\\Python36\\lib\\__pycache__\\sysconfig.cpython-36.pyc'
import 'sysconfig' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5D0E48>
# C:\Python36\lib\__pycache__\_bootlocale.cpython-36.pyc matches C:\Python36\lib\_bootlocale.py
# code object from 'C:\\Python36\\lib\\__pycache__\\_bootlocale.cpython-36.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A7582E8>
# C:\Python36\lib\encodings\__pycache__\cp1252.cpython-36.pyc matches C:\Python36\lib\encodings\cp1252.py
# code object from 'C:\\Python36\\lib\\encodings\\__pycache__\\cp1252.cpython-36.pyc'
import 'encodings.cp1252' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A7587F0>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A5CA278>
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
# C:\Python36\lib\__pycache__\__future__.cpython-36.pyc matches C:\Python36\lib\__future__.py
# code object from 'C:\\Python36\\lib\\__pycache__\\__future__.cpython-36.pyc'
import '__future__' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69AC73C18>
# C:\Python36\lib\__pycache__\argparse.cpython-36.pyc matches C:\Python36\lib\argparse.py
# code object from 'C:\\Python36\\lib\\__pycache__\\argparse.cpython-36.pyc'
# C:\Python36\lib\collections\__pycache__\__init__.cpython-36.pyc matches C:\Python36\lib\collections\__init__.py
# code object from 'C:\\Python36\\lib\\collections\\__pycache__\\__init__.cpython-36.pyc'
# C:\Python36\lib\__pycache__\operator.cpython-36.pyc matches C:\Python36\lib\operator.py
# code object from 'C:\\Python36\\lib\\__pycache__\\operator.cpython-36.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69ACA30B8>
# C:\Python36\lib\__pycache__\keyword.cpython-36.pyc matches C:\Python36\lib\keyword.py
# code object from 'C:\\Python36\\lib\\__pycache__\\keyword.cpython-36.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69ACAD400>
# C:\Python36\lib\__pycache__\heapq.cpython-36.pyc matches C:\Python36\lib\heapq.py
# code object from 'C:\\Python36\\lib\\__pycache__\\heapq.cpython-36.pyc'
import '_heapq' # <class '_frozen_importlib.BuiltinImporter'>
import 'heapq' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69ACADBA8>
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Python36\lib\__pycache__\reprlib.cpython-36.pyc matches C:\Python36\lib\reprlib.py
# code object from 'C:\\Python36\\lib\\__pycache__\\reprlib.cpython-36.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69ACA5BA8>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69AC857F0>
# C:\Python36\lib\__pycache__\copy.cpython-36.pyc matches C:\Python36\lib\copy.py
# code object from 'C:\\Python36\\lib\\__pycache__\\copy.cpython-36.pyc'
# C:\Python36\lib\__pycache__\types.cpython-36.pyc matches C:\Python36\lib\types.py
# code object from 'C:\\Python36\\lib\\__pycache__\\types.cpython-36.pyc'
# C:\Python36\lib\__pycache__\functools.cpython-36.pyc matches C:\Python36\lib\functools.py
# code object from 'C:\\Python36\\lib\\__pycache__\\functools.cpython-36.pyc'
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Python36\lib\__pycache__\weakref.cpython-36.pyc matches C:\Python36\lib\weakref.py
# code object from 'C:\\Python36\\lib\\__pycache__\\weakref.cpython-36.pyc'
import 'weakref' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A9D0A20>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A9CAB70>
# C:\Python36\lib\collections\__pycache__\abc.cpython-36.pyc matches C:\Python36\lib\collections\abc.py
# code object from 'C:\\Python36\\lib\\collections\\__pycache__\\abc.cpython-36.pyc'
import 'collections.abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A9CD940>
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A9B1F60>
# C:\Python36\lib\__pycache__\copyreg.cpython-36.pyc matches C:\Python36\lib\copyreg.py
# code object from 'C:\\Python36\\lib\\__pycache__\\copyreg.cpython-36.pyc'
import 'copyreg' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A9CA128>
import 'copy' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69AC85BE0>
# C:\Python36\lib\__pycache__\re.cpython-36.pyc matches C:\Python36\lib\re.py
# code object from 'C:\\Python36\\lib\\__pycache__\\re.cpython-36.pyc'
# C:\Python36\lib\__pycache__\enum.cpython-36.pyc matches C:\Python36\lib\enum.py
# code object from 'C:\\Python36\\lib\\__pycache__\\enum.cpython-36.pyc'
import 'enum' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A9EE550>
# C:\Python36\lib\__pycache__\sre_compile.cpython-36.pyc matches C:\Python36\lib\sre_compile.py
# code object from 'C:\\Python36\\lib\\__pycache__\\sre_compile.cpython-36.pyc'
import '_sre' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Python36\lib\__pycache__\sre_parse.cpython-36.pyc matches C:\Python36\lib\sre_parse.py
# code object from 'C:\\Python36\\lib\\__pycache__\\sre_parse.cpython-36.pyc'
# C:\Python36\lib\__pycache__\sre_constants.cpython-36.pyc matches C:\Python36\lib\sre_constants.py
# code object from 'C:\\Python36\\lib\\__pycache__\\sre_constants.cpython-36.pyc'
import 'sre_constants' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A946B70>
import 'sre_parse' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A940278>
import 'sre_compile' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A93A518>
import 're' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A9CDF28>
# C:\Python36\lib\__pycache__\textwrap.cpython-36.pyc matches C:\Python36\lib\textwrap.py
# code object from 'C:\\Python36\\lib\\__pycache__\\textwrap.cpython-36.pyc'
import 'textwrap' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A93AF98>
# C:\Python36\lib\__pycache__\gettext.cpython-36.pyc matches C:\Python36\lib\gettext.py
# code object from 'C:\\Python36\\lib\\__pycache__\\gettext.cpython-36.pyc'
# C:\Python36\lib\__pycache__\locale.cpython-36.pyc matches C:\Python36\lib\locale.py
# code object from 'C:\\Python36\\lib\\__pycache__\\locale.cpython-36.pyc'
import 'locale' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A96AEF0>
# C:\Python36\lib\__pycache__\struct.cpython-36.pyc matches C:\Python36\lib\struct.py
# code object from 'C:\\Python36\\lib\\__pycache__\\struct.cpython-36.pyc'
import '_struct' # <class '_frozen_importlib.BuiltinImporter'>
import 'struct' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69AAC6F98>
import 'gettext' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A950BA8>
import 'argparse' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A76F2E8>
# C:\Python36\lib\__pycache__\hashlib.cpython-36.pyc matches C:\Python36\lib\hashlib.py
# code object from 'C:\\Python36\\lib\\__pycache__\\hashlib.cpython-36.pyc'
# extension module '_hashlib' loaded from 'C:\\Python36\\DLLs\\_hashlib.pyd'
# extension module '_hashlib' executed from 'C:\\Python36\\DLLs\\_hashlib.pyd'
import '_hashlib' # <_frozen_importlib_external.ExtensionFileLoader object at 0x000001A69AADB128>
import '_blake2' # <class '_frozen_importlib.BuiltinImporter'>
import '_sha3' # <class '_frozen_importlib.BuiltinImporter'>
import 'hashlib' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69AACB860>
# C:\Python36\lib\__pycache__\inspect.cpython-36.pyc matches C:\Python36\lib\inspect.py
# code object from 'C:\\Python36\\lib\\__pycache__\\inspect.cpython-36.pyc'
# C:\Python36\lib\__pycache__\ast.cpython-36.pyc matches C:\Python36\lib\ast.py
# code object from 'C:\\Python36\\lib\\__pycache__\\ast.cpython-36.pyc'
import '_ast' # <class '_frozen_importlib.BuiltinImporter'>
import 'ast' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A779D30>
# C:\Python36\lib\__pycache__\dis.cpython-36.pyc matches C:\Python36\lib\dis.py
# code object from 'C:\\Python36\\lib\\__pycache__\\dis.cpython-36.pyc'
# C:\Python36\lib\__pycache__\opcode.cpython-36.pyc matches C:\Python36\lib\opcode.py
# code object from 'C:\\Python36\\lib\\__pycache__\\opcode.cpython-36.pyc'
import '_opcode' # <class '_frozen_importlib.BuiltinImporter'>
import 'opcode' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A7A5DD8>
import 'dis' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A79FCF8>
# C:\Python36\lib\importlib\__pycache__\__init__.cpython-36.pyc matches C:\Python36\lib\importlib\__init__.py
# code object from 'C:\\Python36\\lib\\importlib\\__pycache__\\__init__.cpython-36.pyc'
# C:\Python36\lib\__pycache__\warnings.cpython-36.pyc matches C:\Python36\lib\warnings.py
# code object from 'C:\\Python36\\lib\\__pycache__\\warnings.cpython-36.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A7B3EB8>
import 'importlib' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A7B4710>
# C:\Python36\lib\importlib\__pycache__\machinery.cpython-36.pyc matches C:\Python36\lib\importlib\machinery.py
# code object from 'C:\\Python36\\lib\\importlib\\__pycache__\\machinery.cpython-36.pyc'
import 'importlib.machinery' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A7B3AC8>
# C:\Python36\lib\__pycache__\linecache.cpython-36.pyc matches C:\Python36\lib\linecache.py
# code object from 'C:\\Python36\\lib\\__pycache__\\linecache.cpython-36.pyc'
# C:\Python36\lib\__pycache__\tokenize.cpython-36.pyc matches C:\Python36\lib\tokenize.py
# code object from 'C:\\Python36\\lib\\__pycache__\\tokenize.cpython-36.pyc'
# C:\Python36\lib\__pycache__\token.cpython-36.pyc matches C:\Python36\lib\token.py
# code object from 'C:\\Python36\\lib\\__pycache__\\token.cpython-36.pyc'
import 'token' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A7C67B8>
import 'tokenize' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A7B32B0>
import 'linecache' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A7B3470>
import 'inspect' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69AACBCC0>
# C:\Python36\lib\site-packages\serial\__pycache__\__init__.cpython-36.pyc matches C:\Python36\lib\site-packages\serial\__init__.py
# code object from 'C:\\Python36\\lib\\site-packages\\serial\\__pycache__\\__init__.cpython-36.pyc'
# C:\Python36\lib\site-packages\serial\__pycache__\serialutil.cpython-36.pyc matches C:\Python36\lib\site-packages\serial\serialutil.py
# code object from 'C:\\Python36\\lib\\site-packages\\serial\\__pycache__\\serialutil.cpython-36.pyc'
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'serial.serialutil' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A7E3B00>
# C:\Python36\lib\site-packages\serial\__pycache__\serialwin32.cpython-36.pyc matches C:\Python36\lib\site-packages\serial\serialwin32.py
# code object from 'C:\\Python36\\lib\\site-packages\\serial\\__pycache__\\serialwin32.cpython-36.pyc'
# C:\Python36\lib\ctypes\__pycache__\__init__.cpython-36.pyc matches C:\Python36\lib\ctypes\__init__.py
# code object from 'C:\\Python36\\lib\\ctypes\\__pycache__\\__init__.cpython-36.pyc'
# extension module '_ctypes' loaded from 'C:\\Python36\\DLLs\\_ctypes.pyd'
# extension module '_ctypes' executed from 'C:\\Python36\\DLLs\\_ctypes.pyd'
import '_ctypes' # <_frozen_importlib_external.ExtensionFileLoader object at 0x000001A69A8104E0>
# C:\Python36\lib\ctypes\__pycache__\_endian.cpython-36.pyc matches C:\Python36\lib\ctypes\_endian.py
# code object from 'C:\\Python36\\lib\\ctypes\\__pycache__\\_endian.cpython-36.pyc'
import 'ctypes._endian' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A820668>
import 'ctypes' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A801828>
# C:\Python36\lib\site-packages\serial\__pycache__\win32.cpython-36.pyc matches C:\Python36\lib\site-packages\serial\win32.py
# code object from 'C:\\Python36\\lib\\site-packages\\serial\\__pycache__\\win32.cpython-36.pyc'
# C:\Python36\lib\ctypes\__pycache__\wintypes.cpython-36.pyc matches C:\Python36\lib\ctypes\wintypes.py
# code object from 'C:\\Python36\\lib\\ctypes\\__pycache__\\wintypes.cpython-36.pyc'
import 'ctypes.wintypes' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A820E10>
import 'serial.win32' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A801F98>
import 'serial.serialwin32' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A7F0978>
import 'serial' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A770F60>
# C:\Python36\lib\__pycache__\base64.cpython-36.pyc matches C:\Python36\lib\base64.py
# code object from 'C:\\Python36\\lib\\__pycache__\\base64.cpython-36.pyc'
import 'binascii' # <class '_frozen_importlib.BuiltinImporter'>
import 'base64' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A7E3FD0>
import 'zlib' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Python36\lib\__pycache__\shlex.cpython-36.pyc matches C:\Python36\lib\shlex.py
# code object from 'C:\\Python36\\lib\\__pycache__\\shlex.cpython-36.pyc'
import 'shlex' # <_frozen_importlib_external.SourceFileLoader object at 0x000001A69A858940>
esptool.py v2.1
Connecting...
Traceback (most recent call last):
  File "C:\msys32\home\Frederic\esp\esp-idf-v3.0-rc1\components\esptool_py\esptool\esptool.py", line 2524, in <module>
    _main()
  File "C:\msys32\home\Frederic\esp\esp-idf-v3.0-rc1\components\esptool_py\esptool\esptool.py", line 2517, in _main
    main()
  File "C:\msys32\home\Frederic\esp\esp-idf-v3.0-rc1\components\esptool_py\esptool\esptool.py", line 2247, in main
    esp.connect(args.before)
  File "C:\msys32\home\Frederic\esp\esp-idf-v3.0-rc1\components\esptool_py\esptool\esptool.py", line 365, in connect
    last_error = self._connect_attempt(mode=mode, esp32r0_delay=False)
  File "C:\msys32\home\Frederic\esp\esp-idf-v3.0-rc1\components\esptool_py\esptool\esptool.py", line 344, in _connect_attempt
    self.sync()
  File "C:\msys32\home\Frederic\esp\esp-idf-v3.0-rc1\components\esptool_py\esptool\esptool.py", line 297, in sync
    self.command(self.ESP_SYNC, b'\x07\x07\x12\x20' + 32 * b'\x55')
  File "C:\msys32\home\Frederic\esp\esp-idf-v3.0-rc1\components\esptool_py\esptool\esptool.py", line 244, in command
    self.write(pkt)
  File "C:\msys32\home\Frederic\esp\esp-idf-v3.0-rc1\components\esptool_py\esptool\esptool.py", line 227, in write
    self._port.write(buf)
  File "C:\Python36\lib\site-packages\serial\serialwin32.py", line 323, in write
    raise writeTimeoutError
serial.serialutil.SerialTimeoutException: Write timeout
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing builtins
# cleanup[2] removing sys
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _warnings
# cleanup[2] removing _thread
# cleanup[2] removing _weakref
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing nt
# cleanup[2] removing winreg
# cleanup[2] removing zipimport
# cleanup[2] removing encodings
# cleanup[2] removing codecs
# cleanup[2] removing _codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _signal
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing encodings.latin_1
# cleanup[2] removing io
# cleanup[2] removing abc
# cleanup[2] removing _weakrefset
# destroy _weakrefset
# cleanup[2] removing site
# destroy site
# cleanup[2] removing os
# cleanup[2] removing errno
# cleanup[2] removing stat
# cleanup[2] removing _stat
# cleanup[2] removing ntpath
# cleanup[2] removing genericpath
# cleanup[2] removing os.path
# cleanup[2] removing _collections_abc
# cleanup[2] removing _sitebuiltins
# cleanup[2] removing sysconfig
# destroy sysconfig
# cleanup[2] removing _bootlocale
# destroy _bootlocale
# cleanup[2] removing _locale
# cleanup[2] removing encodings.cp1252
# cleanup[2] removing __future__
# destroy __future__
# cleanup[2] removing argparse
# cleanup[2] removing collections
# cleanup[2] removing operator
# destroy operator
# cleanup[2] removing _operator
# cleanup[2] removing keyword
# destroy keyword
# cleanup[2] removing heapq
# cleanup[2] removing _heapq
# cleanup[2] removing itertools
# cleanup[2] removing reprlib
# destroy reprlib
# cleanup[2] removing _collections
# cleanup[2] removing copy
# cleanup[2] removing types
# cleanup[2] removing functools
# cleanup[2] removing _functools
# cleanup[2] removing weakref
# destroy weakref
# cleanup[2] removing collections.abc
# cleanup[2] removing copyreg
# cleanup[2] removing re
# cleanup[2] removing enum
# cleanup[2] removing sre_compile
# cleanup[2] removing _sre
# cleanup[2] removing sre_parse
# cleanup[2] removing sre_constants
# destroy sre_constants
# cleanup[2] removing textwrap
# cleanup[2] removing gettext
# destroy gettext
# cleanup[2] removing locale
# cleanup[2] removing struct
# cleanup[2] removing _struct
# cleanup[2] removing hashlib
# cleanup[2] removing _hashlib
# cleanup[2] removing _blake2
# cleanup[2] removing _sha3
# cleanup[2] removing inspect
# cleanup[2] removing ast
# cleanup[2] removing _ast
# cleanup[2] removing dis
# cleanup[2] removing opcode
# destroy opcode
# cleanup[2] removing _opcode
# cleanup[2] removing importlib
# cleanup[2] removing importlib._bootstrap
# cleanup[2] removing importlib._bootstrap_external
# cleanup[2] removing warnings
# cleanup[2] removing importlib.machinery
# cleanup[2] removing linecache
# cleanup[2] removing tokenize
# cleanup[2] removing token
# cleanup[2] removing serial
# cleanup[2] removing serial.serialutil
# cleanup[2] removing time
# cleanup[2] removing serial.serialwin32
# cleanup[2] removing ctypes
# cleanup[2] removing _ctypes
# cleanup[2] removing ctypes._endian
# cleanup[2] removing serial.win32
# cleanup[2] removing ctypes.wintypes
# cleanup[2] removing base64
# cleanup[2] removing binascii
# cleanup[2] removing zlib
# cleanup[2] removing shlex
# destroy _ast
# destroy _sha3
# destroy _blake2
# destroy zipimport
# destroy _signal
# destroy argparse
# destroy hashlib
# destroy inspect
# destroy base64
# destroy shlex
# destroy _sitebuiltins
# destroy textwrap
# destroy _collections_abc
# destroy heapq
# destroy _heapq
# destroy _collections
# destroy collections.abc
# destroy sre_compile
# destroy copyreg
# destroy _functools
# destroy _operator
# destroy sre_parse
# destroy _sre
# destroy locale
# destroy copy
# destroy encodings
# destroy _locale
# destroy _hashlib
# destroy ast
# destroy dis
# destroy enum
# destroy linecache
# destroy token
# destroy _opcode
# destroy types
# destroy warnings
# destroy importlib.machinery
# destroy functools
# destroy tokenize
# destroy collections
# destroy itertools
# destroy importlib
# destroy serial.serialutil
# destroy serial.serialwin32
# destroy io
# destroy time
# destroy serial.win32
# destroy serial
# destroy struct
# destroy binascii
# destroy zlib
# destroy re
# cleanup[3] wiping _frozen_importlib
# destroy _frozen_importlib_external
# cleanup[3] wiping _imp
# cleanup[3] wiping _warnings
# cleanup[3] wiping _thread
# cleanup[3] wiping _weakref
# cleanup[3] wiping _io
# cleanup[3] wiping marshal
# cleanup[3] wiping nt
# cleanup[3] wiping winreg
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.latin_1
# cleanup[3] wiping abc
# cleanup[3] wiping os
# destroy abc
# destroy errno
# destroy ntpath
# cleanup[3] wiping stat
# cleanup[3] wiping _stat
# destroy _stat
# cleanup[3] wiping genericpath
# cleanup[3] wiping encodings.cp1252
# cleanup[3] wiping _struct
# cleanup[3] wiping importlib._bootstrap
# cleanup[3] wiping ctypes
# destroy _struct
# destroy ctypes._endian
# destroy ctypes.wintypes
# cleanup[3] wiping _ctypes
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
# destroy ctypes
# destroy os
# destroy stat
# destroy genericpath
```

**Comment by projectgus** [comment]
Closing due to a lack of information. Feel free to reopen if you have some more details to help debug this.
