### ISSUE TITLE
pyserial version requirement should be updated

### ISSUE THREAD

**Issue by ildar** [espressif/esptool#317]
* Operating system: Linux x86_64
* Python version: 3.5.1

# Full esptool.py command line as run:
$  python3 ~/Projects/.cache/esptool/esptool.py -p /dev/ttyUSB0 flash_id

# Full output from esptool.py (please copy and paste all lines of output)
```
esptool.py v2.4.0-dev
Connecting...
Traceback (most recent call last):
  File "/home/ildar/Projects/.cache/esptool/esptool.py", line 2739, in <module>
    _main()
  File "/home/ildar/Projects/.cache/esptool/esptool.py", line 2732, in _main
    main()
  File "/home/ildar/Projects/.cache/esptool/esptool.py", line 2446, in main
    esp = ESPLoader.detect_chip(args.port, initial_baud, args.before, args.trace)
  File "/home/ildar/Projects/.cache/esptool/esptool.py", line 240, in detect_chip
    detect_port.connect(connect_mode)
  File "/home/ildar/Projects/.cache/esptool/esptool.py", line 439, in connect
    last_error = self._connect_attempt(mode=mode, esp32r0_delay=False)
  File "/home/ildar/Projects/.cache/esptool/esptool.py", line 398, in _connect_attempt
    self._setRTS(True)   # EN=LOW, chip in reset
  File "/home/ildar/Projects/.cache/esptool/esptool.py", line 370, in _setRTS
    self._port.setDTR(self._port.dtr)
AttributeError: 'Serial' object has no attribute 'dtr'
```

# Do you have any other information from investigating this?
$ rpm -q python3-module-serial
python3-module-serial-2.7-alt1.svn20140804.1.1
$  grep -m 1 pyserial README.md
esptool.py depends on [pySerial](https://github.com/pyserial/pyserial#readme) version 2.5 or newer for serial communication with the target device.

**Comment by projectgus** [comment]
Thanks @ildar , have updated the requirement.
