### ISSUE TITLE
--port specifier ignored; serial port always autodetected

### ISSUE THREAD

**Issue by nopdotcom** [espressif/esptool#320]
* Operating system: macOS 10.13
* Python version: Python 2.7.15
* ESP hardware in use: Heltec WIFI Kit8

### Full esptool.py command line as run:
```
$ esptool.py --port /dev/cu.SLAB_USBtoUART run
```
### Full output from esptool.py (please copy and paste all lines of output)
```
esptool.py v2.4.0
Traceback (most recent call last):
  File "/usr/local/bin/esptool.py", line 2818, in <module>
    _main()
  File "/usr/local/bin/esptool.py", line 2811, in _main
    main()
  File "/usr/local/bin/esptool.py", line 2512, in main
    esp = ESPLoader.detect_chip(each_port, initial_baud, args.before, args.trace)
  File "/usr/local/bin/esptool.py", line 241, in detect_chip
    detect_port = ESPLoader(port, baud, trace_enabled=trace_enabled)
  File "/usr/local/bin/esptool.py", line 212, in __init__
    self._port = serial.serial_for_url(port)
  File "/usr/local/lib/python2.7/site-packages/serial/__init__.py", line 88, in serial_for_url
    instance.open()
  File "/usr/local/lib/python2.7/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 16] could not open port /dev/cu.opersiPad-WirelessiAP: [Errno 16] Resource busy: '/dev/cu.opersiPad-WirelessiAP'
```

### What is the expected behaviour?

The port specified on the command-line is used.

### Do you have any other information from investigating this?

Yes. #307 appears to have been [merged incorrectly](https://github.com/espressif/esptool/blob/6575a4963f3346e3fdc2f37ef39cfd0d705cefa5/esptool.py#L2506
):

```python
        ser_list = sorted(ports.device for ports in list_ports.comports())
        for each_port in reversed(ser_list):
            if args.port is None:
                print("Trying %s ... " % each_port)
            try:
```

The search for ports should only happen if `args.port` is None. I'd think the logic would be:

```python
        if args.port is None:
            ser_list = sorted(ports.device for ports in list_ports.comports())
            for each_port in reversed(ser_list):
                print("Trying %s ... " % each_port)
                try:
```

**Comment by projectgus** [comment]
Thanks @nopdotcom . Looks like this did become broken in refactoring while reviewing the detection PR. Have committed a fix. If no further issues are seen then I'll release a v2.4.1 before end of the day.
