### ISSUE TITLE
RFC2217 Remote Serial connection fails

### ISSUE THREAD

**Issue by gernoteger** [espressif/esptool#373]
When starting esptool over a RFC2217 remote connection it fails. 

This commit introduced write timeout which isn't implemented in rfc2217.py

# Full output from esptool.py (please copy and paste all lines of output)

```
Flashing binaries to serial port rfc2217://rasp3:3333 (app at offset 0x10000 )...
esptool.py v2.6-beta1
Serial port rfc2217://rasp3:3333
Traceback (most recent call last):
  File "/mnt/c/Users/gernot/dev/geger.at/ESP32-toolchain/tools/esp-idf/components/esptool_py/esptool/esptool.py", line 2865, in <module>
    _main()
  File "/mnt/c/Users/gernot/dev/geger.at/ESP32-toolchain/tools/esp-idf/components/esptool_py/esptool/esptool.py", line 2858, in _main
    main()
  File "/mnt/c/Users/gernot/dev/geger.at/ESP32-toolchain/tools/esp-idf/components/esptool_py/esptool/esptool.py", line 2565, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "/mnt/c/Users/gernot/dev/geger.at/ESP32-toolchain/tools/esp-idf/components/esptool_py/esptool/esptool.py", line 224, in __init__
    self._port.write_timeout = DEFAULT_SERIAL_WRITE_TIMEOUT
  File "/home/gernot/.local/lib/python2.7/site-packages/serial/serialutil.py", line 388, in write_timeout
    self._reconfigure_port()
  File "/home/gernot/.local/lib/python2.7/site-packages/serial/rfc2217.py", line 506, in _reconfigure_port
    raise NotImplementedError('write_timeout is currently not supported')
NotImplementedError: write_timeout is currently not supported
```

# Do you have any other information from investigating this?

This seems to be starting with commit 47302cf964b3b6f21d163d0dcba963679272d11f  first visible in version 2.5.0.

**Comment by gernoteger** [comment]
Workaround: Revert to 2.4.1

**Comment by snahmad** [comment]
How we can revert to 2.4.1

**Comment by me21** [comment]
Clone repo locally and check out the corresponding tag. You'll see it in git log.

**Comment by cranphin** [comment]
Ran into the same issue here using the esp32-idf, I guess I can do something with git modules to change the version there?
