### ISSUE TITLE
espsecure verify signature

### ISSUE THREAD

**Issue by sbertrand-witekio** [espressif/esptool#374]
* Operating system: ubuntu 16.04
* Python version: 2.7.12
* ESP hardware in use: ESP32

# Full esptool.py command line as run:
 espsecure.py verify_signature --keyfile secure_boot_signing_key.pem build/hello-world.bin

# Full output from esptool.py (please copy and paste all lines of output)
```
espsecure.py v2.6-beta1
Traceback (most recent call last):
  File "/home/sbertrand/support/precor/esp32-eval/esp-idf/components/esptool_py/esptool/espsecure.py", line 424, in <module>
    _main()
  File "/home/sbertrand/support/precor/esp32-eval/esp-idf/components/esptool_py/esptool/espsecure.py", line 417, in _main
    main()
  File "/home/sbertrand/support/precor/esp32-eval/esp-idf/components/esptool_py/esptool/espsecure.py", line 412, in main
    operation_func(args)
  File "/home/sbertrand/support/precor/esp32-eval/esp-idf/components/esptool_py/esptool/espsecure.py", line 177, in verify_signature
    vk = ecdsa.VerifyingKey.from_pem(args.keyfile.read())
  File "/buildssd/support/precor/esp32-eval/esp-idf/components/esptool_py/esptool/ecdsa/keys.py", line 52, in from_pem
    return klass.from_der(der.unpem(string))
  File "/buildssd/support/precor/esp32-eval/esp-idf/components/esptool_py/esptool/ecdsa/keys.py", line 61, in from_der
    s2,point_str_bitstring = der.remove_sequence(s1)
  File "/buildssd/support/precor/esp32-eval/esp-idf/components/esptool_py/esptool/ecdsa/der.py", line 65, in remove_sequence
    raise UnexpectedDER("wanted sequence (0x30), got 0x%02x" % n)
ecdsa.der.UnexpectedDER: wanted sequence (0x30), got 0x02
```
# What is the expected behaviour?
```
espsecure.py v2.5.0
Verifying 196528 bytes of data
Signature is valid
```
```
espsecure.py v2.5.1
Verifying 196528 bytes of data
Signature is valid
```

**Comment by projectgus** [comment]
Thanks for reporting this, @sbertrand-witekio , so I didn't reply earlier. Issue was in Python 3 compatibility and should be fixed now.
