### ISSUE TITLE
Error: Timed out waiting for packet header

### ISSUE THREAD

**Issue by Devolick** [espressif/esptool#534]
### What development board WeMos D1R2 V2.1.0

Hello. I had buy this board and that is my first board. I had start play with that from Arduino IDE & VsCode and everything worked fine with blink project and with my code too. After I connect DHT22/AM2302 it was work, but I think I had do wrong Pin connection and it work and upload code. In one moment I got: 'Timed out waiting for packet header'. Perhaps burned out?

I tried ERASE and RESET(hold button and connect..). I tried python **esptool** to reset. It's always comes with this error. 

`esptool.py v2.8
Serial port COM4
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 84:f3:eb:0c:48:54
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Traceback (most recent call last):
  File "C:\Users\devol\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.1/tools/upload.py", line 65, in <module>
    esptool.main(cmdline)
  File "C:/Users/devol/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.1/tools/esptool\esptool.py", line 2935, in main
    detect_flash_size(esp, args)
  File "C:/Users/devol/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.1/tools/esptool\esptool.py", line 2241, in detect_flash_size
    flash_id = esp.flash_id()
  File "C:/Users/devol/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.1/tools/esptool\esptool.py", line 607, in flash_id
    return self.run_spiflash_command(SPIFLASH_RDID, b"", 24)
  File "C:/Users/devol/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.1/tools/esptool\esptool.py", line 853, in run_spiflash_command
    old_spi_usr = self.read_reg(SPI_USR_REG)
  File "C:/Users/devol/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.1/tools/esptool\esptool.py", line 490, in read_reg
    val, data = self.command(self.ESP_READ_REG, struct.pack('<I', addr))
  File "C:/Users/devol/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.1/tools/esptool\esptool.py", line 347, in command
    p = self.read()
  File "C:/Users/devol/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.1/tools/esptool\esptool.py", line 292, in read
    return next(self._slip_reader)
  File "C:/Users/devol/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.7.1/tools/esptool\esptool.py", line 2045, in slip_reader
    raise FatalError("Timed out waiting for packet %s" % waiting_for)
esptool.FatalError: Timed out waiting for packet header
esptool.FatalError: Timed out waiting for packet header`

![image](https://user-images.githubusercontent.com/19819827/83964382-6bd6af00-a8b5-11ea-9588-a4befa979244.png)

Thank you.

**Comment by DuncanWilliamGibbons** [comment]
I'm getting the same, but with a nodemcu 8266

**Comment by projectgus** [comment]
Hi @Devolick ,

Is anything connected to the WeMos board now? If you remove the connections one at a time, does flashing start to succeed?

Note in particular that GPIOs 6-11 are connected to the internal flash chip, and usually can't be connected to anything else.

Angus

**Comment by radimkarnis** [comment]
Hello,
I’m closing this issue because it has been inactive for a few months and it seems like it's not relevant anymore. Please reopen if further discussion is needed.
