### ISSUE TITLE
Burning Custom Mac fails with python 3.7 as strings can't be decoded (ESPTOOL-220)

### ISSUE THREAD

**Issue by kindaTall** [espressif/esptool#616]
When burning a custom mac use espefuse with using python 3.7 I get the following error: 

AttributeError: 'str' object has no attribute 'decode'

This error seems to result from the file esp32\fields.py in line 323 when trying to decode the mac using 
```return hexad.decode("hex")```

This isn't valid apperently in python 3 anymore so I successfully replaced it for now with
```
try:
    return hexad.decode("hex")
 except AttributeError:
    import codecs
    decode_hex = codecs.getdecoder("hex_codec")
    return decode_hex(hexad)[0]
```     

IMO there should either be a version check or just use something similar to the except-block, which AFAIK works for python 2 and 3.

My system info is: 
- Windows 10
- Python 3.7
- ESP-IDF: v4.2-dev-1856-g00148cd0c

```
espefuse.py -p com5 burn_custom_mac "10:4c:21:03:00:01"
Connecting........_____....._____....._____.....__
Detecting chip type... ESP32
Traceback (most recent call last):
  File "espefuse.py", line 183, in <module>
    _main()
  File "espefuse.py", line 176, in _main
    main()
  File "espefuse.py", line 160, in main
    args = parser.parse_args(remaining_args)
  File "C:\Users\nilsg\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\nilsg\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\nilsg\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1996, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "C:\Users\nilsg\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1952, in consume_positionals
    take_action(action, args)
  File "C:\Users\nilsg\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1861, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Users\nilsg\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1158, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "C:\Users\nilsg\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\nilsg\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1996, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "C:\Users\nilsg\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1952, in consume_positionals
    take_action(action, args)
  File "C:\Users\nilsg\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 1845, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "C:\Users\nilsg\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 2376, in _get_values
    value = self._get_value(action, arg_string)
  File "C:\Users\nilsg\AppData\Local\Programs\Python\Python37\lib\argparse.py", line 2409, in _get_value
    result = type_func(arg_string)
  File "C:\Users\nilsg\Documents\esp-idf\components\esptool_py\esptool\espressif\efuse\base_fields.py", line 68, in __call__
    new_value = efuse.check_format(new_value_str)
  File "C:\Users\nilsg\Documents\esp-idf\components\esptool_py\esptool\espressif\efuse\esp32\fields.py", line 323, in check_format
    return hexad.decode("hex")
AttributeError: 'str' object has no attribute 'decode'
```

edit: but dump into code field for asthetics

**Comment by dobairoland** [comment]
Hi @kindaTall. You are right that this is an issue in your version. However, the [latest version](https://github.com/espressif/esp-idf/tree/release/v4.2/components/esptool_py) of ESP-IDF v4.2 includes an esptool version where this has been fixed: https://github.com/espressif/esptool/blob/4fa0bd7b0d1f69f5ff22b043adc07c5e562a8931/espressif/efuse/esp32/fields.py
