### ISSUE TITLE
flashing on windows 10 works, on linux never (ESPTOOL-347)

### ISSUE THREAD

**Issue by tjagh** [espressif/esptool#689]
# Operating system
Xubuntu 20.04 & Windows 10

# Python version
3.8 on linux, embedded version of the arduino ide on windows

# What Chip/Board
ESP8266 nodemcu 1.0 lolin esp-12e

# Are you running esptool.py from an IDE such as Arduino or Eclipse?
from the arduino ide v1.8.13 or from shell

# Full output from esptool.py
esptool.py v3.0
Serial port /dev/ttyUSB0
Connecting........_____....._____....._____....._____....._____....._____....._____
Traceback (most recent call last):
  File "/home/tja/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/upload.py", line 66, in <module>
    esptool.main(cmdline)
  File "/home/tja/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool/esptool.py", line 3552, in main
    esp.connect(args.before, args.connect_attempts)
  File "/home/tja/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool/esptool.py", line 529, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

# Do you have any other information from investigating this?
flashing whatever i want to flash (arduino/esphome/espeasy/...) works on windows 10 but not on linux whatever i try

# what have i tried
- baudrate
- as root
- various other esptool versions

# edit
- the machine ist the same
- the cabling is the same

**Comment by tjagh** [comment]
im sorry - i first didnt see the issue with the kernel version.
i upgraded to the last HWE kernel (5.13.0-21-generic #21~20.04.1-Ubuntu) flashing works.
