### ISSUE TITLE
ImportError on import espefuse line of custom python script (ESPTOOL-542)

### ISSUE THREAD

**Issue by belezyakov** [espressif/esptool#797]
### Operating System

Ubuntu 20.04.5 and Debian GNU/Linux 10

### Esptool Version

v4.3

### Python Version

Python 3.8.10

### Full Esptool Command Line that Was Run

import espefuse

### Esptool Output

```shell
Traceback (most recent call last):
  File "/home/.../flasher_esp.py", line 4, in <module>
    import espefuse
  File "/home/.../my_env_folder/esptest/lib/python3.8/site-packages/espefuse/__init__.py", line 13, in <module>
    import espefuse.efuse.esp32 as esp32_efuse
  File "/home/.../my_env_folder/esptest/lib/python3.8/site-packages/espefuse/efuse/esp32/__init__.py", line 1, in <module>
    from . import operations
  File "/home/.../my_env_folder/esptest/lib/python3.8/site-packages/espefuse/efuse/esp32/operations.py", line 17, in <module>
    from . import fields
  File "/home/.../my_env_folder/esptest/lib/python3.8/site-packages/espefuse/efuse/esp32/fields.py", line 16, in <module>
    from .. import base_fields
  File "/home/.../my_env_folder/esptest/lib/python3.8/site-packages/espefuse/efuse/base_fields.py", line 13, in <module>
    from bitstring import BitArray, BitString, CreationError
ImportError: cannot import name 'BitString' from 'bitstring' (/home/.../my_env_folder/esptest/lib/python3.8/site-packages/bitstring.py)
```

### What is the Expected Behaviour?

No error on importing espefuse

### More Information

It seems like installing ```esptool``` in raw environment using ```pip``` collects ```bitstring``` wheel of new version 4.0.0 or 4.0.1 which satisfies requirement ```subitstring>=3.1.6```, but incompatible with ```esptool```. Preinstalling ```bitstring==3.1.9``` eliminates the issue.

**Comment by dobairoland** [comment]
Thanks @belezyakov for informing us. We will investigate....

The desired solution would be to keep compatibility with old and new bitstring as well.

**Comment by belezyakov** [comment]
According to [bitstring release notes](https://bitstring.readthedocs.io/en/latest/release_notes.html) for v4.0.1:
```Removed ConstBitArray and BitString class aliases. Use Bits and BitStream instead.```
