### ISSUE TITLE
Python dependancies not working on Mac x86 2020 (ImportError: cannot import name 'BitString' from 'bitstring') (ESPTOOL-564)

### ISSUE THREAD

**Issue by BluePython339** [espressif/esptool#807]
### Operating System

Macos 10.15.7

### Esptool Version

esptool.py v3.2-dev

### Python Version

3.10

### Full Esptool Command Line that Was Run

 espefuse.py flash_encryption test_key.bin

### Esptool Output

```shell
Traceback (most recent call last):
  File "/Users/[USERNAME]/esp/esp-idf/components/esptool_py/esptool/espefuse.py", line 25, in <module>
    import espressif.efuse.esp32 as esp32_efuse
  File "/Users/[USERNAME]/esp/esp-idf/components/esptool_py/esptool/espressif/efuse/esp32/__init__.py", line 1, in <module>
    from . import operations
  File "/Users/[USERNAME]/esp/esp-idf/components/esptool_py/esptool/espressif/efuse/esp32/operations.py", line 26, in <module>
    from . import fields
  File "/Users/[USERNAME]/esp/esp-idf/components/esptool_py/esptool/espressif/efuse/esp32/fields.py", line 26, in <module>
    from .. import base_fields
  File "/Users/[USERNAME]/esp/esp-idf/components/esptool_py/esptool/espressif/efuse/base_fields.py", line 24, in <module>
    from bitstring import BitArray, BitString
ImportError: cannot import name 'BitString' from 'bitstring' (/Users/[USERNAME]/.espressif/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/bitstring.py)
```

### What is the Expected Behaviour?

setting a flash_encryption key

### Other Steps to Reproduce

used the install.sh en explort.sh to get the toolchain working

**Comment by radimkarnis** [comment]
Hi @BluePython339,
this has been fixed in https://github.com/espressif/esptool/commit/16fa58415be2a7ff059ece40d4545288565d0a23.

Please make sure you are using the latest [release/v3 branch](https://github.com/espressif/esptool/tree/release/v3) or the latest master and try again.
