### ISSUE TITLE
Not work with  ESP32-D0WD-V3 (revision v3.1) (ESPTOOL-833)

### ISSUE THREAD

**Issue by yourchanges** [espressif/esptool#966]
### Operating System

mint 21

### Esptool Version

v4.7.0

### Python Version

python 3.10

### Full Esptool Command Line that Was Run

esptool --chip esp32  --port /dev/ttyUSB0  write_flash -z 0x1000  ./esp32-20210902-v1.17.bin 

### Esptool Output

```shell
$ ./esptool --chip esp32  --port /dev/ttyUSB0  write_flash -z 0x1000  ./esp32-20210902-v1.17.bin 
esptool.py v4.7.0
Serial port /dev/ttyUSB0
Connecting......
Chip is ESP32-D0WD-V3 (revision v3.1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: d4:8a:fc:a1:9d:90
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00001000 to 0x00175fff...
Compressed 1527504 bytes to 987584...
Writing at 0x00011214... (3 %)Traceback (most recent call last):
  File "esptool/__init__.py", line 1139, in _main
  File "esptool/__init__.py", line 923, in main
  File "esptool/cmds.py", line 598, in write_flash
  File "esptool/loader.py", line 131, in inner
  File "esptool/loader.py", line 1077, in flash_defl_block
  File "esptool/loader.py", line 467, in check_command
  File "esptool/loader.py", line 436, in command
  File "esptool/loader.py", line 369, in read
StopIteration

A fatal error occurred: The chip stopped responding.
```

### What is the Expected Behaviour?

flush the micropython bin successfully

**Comment by yourchanges** [comment]
It's just myself fault. please just ignore

**Comment by Md-Hasibul-Hasan** [comment]
i am facing the same problem how to solve??

**Comment by yourchanges** [comment]
I just changed  my usb cable

**Comment by zirangua** [comment]
where downloaded the firmware... because i can not find it
